name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  full-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build release version
        run: ./build.sh release
      - name: Build debug version
        run: ./build.sh debug
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path:
            build
